version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3300:3300"

  web:
    build: .
    command: bundle exec rails s -p 3010 -b '0.0.0.0'
    volumes:
      - .:/app_name
    ports:
      - "3010:3010"
    tty: true
    stdin_open: true
    links:
      - db
